language: perl
perl:
- '5.22'
- '5.20'
- '5.18'
notifications:
  slack:
    secure: W4W5EePPHPZsQkoDj2G4Kje+fdAFA9dqxF8VtCNaHjpzAGDhWfsg93iYkuI+JgQNQTSgiJYt4V6wSTMjz627H5Zl1KOnO/PmOs1tmPn+9cE6FBHHqoLJwc9+wVJX/PlpiuesjDOB7fhw7ZXtQsk6xRkiuKEji/8eIRPGgI7JxfoFBLtANPkdF7iKE8B3jhUpU9urvobxjrPfUt3BfAoyjliuEvrMISURalOQujHzpatcPcA3Tb+AEA5yvuhkyzSVsOyLWD5oR6Rc4/LGaMH57JinmyBhkEeab4iIfaPEZYkBsM5MIQn4ZmZhTtw17c+wQy3oC8XiJZ6It8bPmhOpn5wPjzK0mozSZ4E3WVtLxCfu4yqQGrdaj/xiEuL3fif1iDLRDe9OSP0L8NOwzRLhSs5th2z8L+BbFBx3taEPN+ZglXs/h817dq71A7SG7kFx9+u/gs7hRJRfIDUP8EaCpjqNrRPPZLo5sJ7i9bemfkdK9dzPqxOEFEay31yL9x8W2ugYHju17fEDM7hAwNzQ6NvT4Bo7nw2nLaYOuZCkdHAMh544wqJlf3cZjZwsZDmvFsMUTZzTA3QSsgMZS/wokwZhnGXxLHMkfBbRg2fmcv4ZlAVXCqkZAHoZdUnmKF7V0g+F7/rFkcc7Nqax0f8Q67pLxrwyObhj2Dzfwvkw4QU=

